-- CATEGORIES
INSERT INTO categories (`name`, `created_at`, `updated_at`) VALUES ('Electronics', NOW(), NOW());
INSERT INTO categories (`name`, `created_at`, `updated_at`) VALUES ('Jewelery', NOW(), NOW());
INSERT INTO categories (`name`, `created_at`, `updated_at`) VALUES ('Men''s clothing', NOW(), NOW());
INSERT INTO categories (`name`, `created_at`, `updated_at`) VALUES ('Women''s clothing', NOW(), NOW());

-- PRODUCTS: ELECTRONICS
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (1, 'WD 2TB Portable External Hard Drive', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 64.50, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 10, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (1, 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)', 120, 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 5, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (1, 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty', 115.90, 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 2, 1, NOW(), NOW());

-- PRODUCTS: JEWELERY
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (2, 'Solid Gold Petite Micropave', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.', 170, 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg', 4, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (2, 'White Gold Plated Princess', 'Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine''s Day.', 9.99, 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg', 15, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (2, 'Pierced Owl Rose Gold Plated Stainless Steel Double', 'Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel', 10.99, 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg', 3, 1, NOW(), NOW());

-- PRODUCTS: Men's clothing
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (3, 'Men''s Casual Premium Slim Fit T-Shirts', 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.', 24.50, 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg', 5, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (3, 'Men''s Cotton Jacket', 'great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.', 55, 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg', 2, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (3, 'Men''s Casual Slim Fit', 'The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.', 15.99, 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg', 6, 1, NOW(), NOW());

-- PRODUCTS: Women's clothing
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (4, 'Rain Jacket Women Windbreaker Striped Climbing Raincoats', 'Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn''t overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.', 35.99, 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg', 2, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (4, 'MBJ Women''s Solid Short Sleeve Boat Neck V', '95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem.', 8.50, 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg', 3, 1, NOW(), NOW());
INSERT INTO products (`category_id`, `name`, `description`, `price`, `image`, `qty`, `visible`, `created_at`, `updated_at`) VALUES (4, 'Opna Women''s Short Sleeve Moisture', '100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort.', 9.50, 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg', 7, 1, NOW(), NOW());

-- CARTS
INSERT INTO carts (`created_at`, `updated_at`) VALUES (NOW(), NOW());

-- WISHLIST
INSERT INTO wishlists (`created_at`, `updated_at`) VALUES (NOW(), NOW());